General:
  trainer: FedTL
  model: FedAvgCNN
  dataset: MNIST.non_iid_1

Trainer: 
  C: 1.0
  E: 1
  total_epoch: 2000
  lambda: 0.01
  lambda_decay: 1.0
  n_clients: 10
  test_interval: 1
  device: cpu
  batch_size: 100
  optimizer:
    lr: 0.03
    momentum: 0.0
    weight_decay: 0.0
    lr_decay: 0.98

