Dataset:
  name: MNIST
  divide: non_iid_shard
  #s: 0.1
  shard_per_user: 2

Model: 
  name: FedAvg2NN
  input_shape: [1, 28, 28]
  cls_num: 10

Trainer: 
  name: FedTL
  seed: 0
  C: 1.0
  E: 1
  Round: 200
  lambda: 0.0001
  #eta_g: 1.0
  n_clients: 10
  test_interval: 1
  device: cpu
  batch_size: 100
  optimizer:
    lr: 0.1
    momentum: 0.0
    weight_decay: 0.0
    lr_decay: 0.992

