Output: './output.txt'

Dataset:
  name: MNIST
  divide: non_iid_percent
  #####Divide Parameters#####
  # non_iid_percent
  s: 0.0
  # non_iid_shard
  # shard_per_user: 2
  #####Divide Parameters#####

Model: 
  name: FedAvg2NN
  input_shape: [1, 28, 28]
  cls_num: 10

Trainer: 
  name: FedAvg
  seed: 0
  C: 1.0
  E: 1
  Round: 300
  n_clients: 10
  test_interval: 1
  device: cpu
  batch_size: 100
  #####Trainer Parameters#####
  # qfedavg
  # L: 1.0
  # q: 0.1
  # rfedavg
  # lambda: 0.0001
  # fedprox
  # lambda: 0.5
  # SCAFFOLD
  # eta_g: 1.0
  #####Trainer Parameters#####
  optimizer:
    lr: 0.1
    momentum: 0.0
    weight_decay: 0.0
    lr_decay: 1.0

