Dataset:
  name: EMNIST
  divide: non_iid_percent
  s: 0.1
  #shard_per_user: 2

Model: 
  name: LogisticRegression
  input_shape: [1, 28, 28]
  cls_num: 62

Trainer: 
  name: SCAFFOLD
  seed: 0
  C: 0.2
  E: 1
  T: 100
  #lambda: 0.00001
  eta_g: 1.0
  n_clients: 100
  test_interval: 1
  device: cpu
  batch_size: 1400
  optimizer:
    lr: 0.1
    momentum: 0.0
    weight_decay: 0.0
    lr_decay: 0.992

