General:
  trainer: FedTL
  model: FedAvgCNN
  dataset: CIFAR10.non_iid_1

Trainer: 
  C: 1.0
  E: 1
  total_epoch: 2000
  lambda: 0.00001
  eta_g: 1.0
  lambda_decay: 1.0
  n_clients: 10
  test_interval: 1
  device: cpu
  batch_size: 100
  optimizer:
    lr: 0.1
    momentum: 0.0
    weight_decay: 0.0
    lr_decay: 0.992

